spring:
  datasource:
    url: jdbc:postgresql://dpg-d1oe3n3uibrs73clib30-a:5432/hotel_db_pfuc
    username: hotel_db_pfuc_user
    password: PZtCXKljb3uImCk7SJfXvQ7hfmzmF4WR
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
hotel:
  app:
    jwtSecret: N+MqAD3gPyWpd4ReIwb5XZkVGuqrpgd1+FQUMNTFrrk=
    jwtExpirationMs: 3600000
