spring:
  datasource:
    url: jdbc:postgresql://ikramshoteldb2025.postgres.database.azure.com:5432/hoteldb?sslmode=require
    username: postgres@ikramshoteldb2025  # Format Azure obligatoire
    password: ${DB_PASSWORD}  # À définir dans Azure App Service
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
hotel:
  app:
    jwtSecret: N+MqAD3gPyWpd4ReIwb5XZkVGuqrpgd1+FQUMNTFrrk=
    jwtExpirationMs: 3600000
