spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_hotel_db
    username: postgres
    password: ikram
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

hotel:
  app:
    jwtSecret: N+MqAD3gPyWpd4ReIwb5XZkVGuqrpgd1+FQUMNTFrrk=
    jwtExpirationMs: 3600000
