spring:
  datasource:
    url: jdbc:postgresql://ikramshoteldb2025.postgres.database.azure.com:5432/postgres?sslmode=require
    username: postgres
    password: Febrex123
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

hotel:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${JWT_EXPIRATION_MS}
