spring:
  datasource:
    url: ${DATABASE_URL}
    username: postgres
    password: dOHgfvJbrWWRURVciJbjYHxWkGhWqUOk
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
