spring:
  datasource:
    url: jdbc:postgresql://ikramshoteldb2025.postgres.database.azure.com:5432/hoteldb
    username: postgres
    password: Febrex123
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
hotel:
  app:
    jwtSecret: dev-secret-123456
    jwtExpirationMs: 3600000
